import React from 'react'
import './about.css'

export const About = () => {
  return (
    <div className='about-div'>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veniam quisquam facere iste, ipsa amet ipsum sapiente tempora, earum ut in facilis architecto porro eos sed. Magni ea iste reiciendis quo cupiditate nam illum similique quos quaerat iure non tempora vitae quisquam obcaecati neque fugit adipisci odio, corrupti id voluptatibus mollitia omnis blanditiis sint. Pariatur soluta doloribus facilis, voluptas atque temporibus ut quis natus tenetur? Est et iusto, ipsum eaque qui unde laboriosam, inventore sint, dolores alias illo nemo dignissimos vel deserunt quam fugit voluptas eos id ipsa aliquid accusamus! Rem voluptatem nihil, iusto soluta deserunt nostrum est odio itaque ipsam distinctio doloremque dolor excepturi sequi magni inventore quo laboriosam expedita consequuntur? Libero harum nobis doloremque vero corporis voluptate consequatur iure magnam facere eum, placeat numquam illum. Incidunt maxime eligendi quas, illum facilis fugit alias iusto! Et earum molestiae incidunt, ut atque autem aliquid reiciendis ex. Perspiciatis repellat expedita odit voluptas dolore veniam animi dignissimos exercitationem officia? Architecto velit, amet molestiae nemo, excepturi perferendis omnis earum, facilis dicta reprehenderit vitae eum beatae repellat qui? Ipsam accusamus quos molestias autem vel expedita id temporibus error enim tempora illum nemo doloribus dignissimos aspernatur, minima perferendis voluptatibus in quisquam perspiciatis vero ducimus eligendi tenetur consequatur. Ipsa molestias eius perferendis tempora maiores quaerat, ipsum quas necessitatibus dolores illum voluptatum delectus voluptate iusto, dolorem debitis et officia fugiat saepe corrupti omnis repudiandae qui itaque blanditiis ducimus! Temporibus, corrupti! In similique sapiente adipisci fuga, debitis maxime qui! Ad, quia quidem. Architecto consectetur, accusantium possimus veniam culpa repellendus corrupti quaerat nobis nam quam in sunt amet. Iusto voluptatum quae, rem temporibus ratione sed, nulla repellat eaque illo soluta ab totam reprehenderit velit? Aut quibusdam explicabo facere aliquid amet quae dignissimos ut repudiandae ipsum perferendis tenetur, eligendi totam iusto, laborum iste. Error rem nisi dignissimos consectetur harum nesciunt aliquam.</p>
    </div>
 )
}
